---
title: "1-data-filtering"
author: "Skye Davis"
date: "2026-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Workflow
This script takes the unfiltered SNP data generated by DArTseq (SNPs called using DArT’s proprietary pipeline DArTSoft14TM) and performs basic locus and sample level filtering, excluding close relatives filtering.


# Set up

```{r Packages}

# For basic filtering
library(dartR) # v2.9.7

# For duplicate filtering
library(SNPRelate) # v1.30.1
library(gdsfmt) # v1.32.0

# For outlier filtering
library(qvalue) # v2.28.0 

# For plotting
library(ggplot2) # v3.5.1

# Other attached packages
library(adegenet) # v2.1.10
library(ade4) # v1.7-22

```

```{r Directories}

# Main directory for data
data_dir <- paste0(getwd(),"/data")

# Input data directory for this script
input_data_dir <- paste0(data_dir,"/unfiltered-dart-data")

# Output data directory for this script
output_data_dir <- paste0(data_dir,"/filtered-dart-data")
dir.create(output_data_dir, recursive = TRUE)

# Results directories for this script

dups_result_dir <- paste0(getwd(),"/results/1-data-filtering/1.2-duplicate-filtering")
dir.create(dups_result_dir, recursive = TRUE)
dir.create(paste0(dups_result_dir,"/_PLOTS"), recursive = TRUE)

outlier_result_dir <- paste0(getwd(),"/results/1-data-filtering/1.3-outlier-filtering")
dir.create(outlier_result_dir, recursive = TRUE)
dir.create(paste0(outlier_result_dir,"/_PLOTS"), recursive = TRUE)

```

# Analysis

## 1.1 dartR filtering

```{r dartR filtering}

# Import unfiltered data (DArT unfiltered SNPs)
setwd(input_data_dir)
unfiltered <- gl.read.dart(filename = "Report_DPoep23-8916_1_moreOrders_SNP_mapping_2-renamed.csv", 
                           ind.metafile = "BTF_pop_info.csv")

# Sort pops in preferred order for plotting later
mypoporder <- c("North", "Central", "South")
unfiltered_sorted <- gl.sort(unfiltered, sort.by = "pop", order.by = mypoporder)

# 1. Monomorph filter
filter1 <- gl.filter.monomorphs(unfiltered_sorted)

# 2. Reproducibility filter
filter2 <- gl.filter.reproducibility(filter1, threshold = 0.98, plot.out = TRUE)

# 3. Depth of coverage filter
rd <- mean(filter2@other$loc.metrics$rdepth)
sd <- sd(filter2@other$loc.metrics$rdepth)
upper <- (rd + 3*sd)
filter3 <- gl.filter.rdepth(filter2, lower = 8, upper = upper, plot.out = TRUE)

# 4. Iterative callrate filters (by individual and locus)
filter4.1 <- gl.filter.callrate(filter3, method = "ind", threshold = 0.6, recalc = TRUE,mono.rm = TRUE)
filter4.2 <- gl.filter.callrate(filter4.1, method = "loc", threshold = 0.6, recalc = TRUE, mono.rm = TRUE)
filter4.3 <- gl.filter.callrate(filter4.2, method = "ind", threshold = 0.80, recalc = TRUE, mono.rm = TRUE)
filter4.4 <- gl.filter.callrate(filter4.3, method = "loc", threshold = 0.95, recalc = TRUE, mono.rm = TRUE)
filter4.5 <- gl.filter.callrate(filter4.4, method = "ind", threshold = 0.90, recalc = TRUE, mono.rm = TRUE)

# 5. MAF filter
filter5 <- gl.filter.maf(filter4.5, threshold = 3)

# 6. Secondaries filter
filter6 <- gl.filter.secondaries(filter5, method = "random")

# 7. HWE filter (within pops only)
filter7 <- gl.filter.hwe(filter6, subset = "each", n.pop.threshold = 3, method_sig = "Exact", multi_comp = TRUE, multi_comp_method = "fdr", alpha_val = 0.05, pvalue_type = "midp", cc_val = 0.5, min_sample_size = 6)

# Save output
setwd(output_data_dir)
saveRDS(filter7, file = "filter7-HWE.RData")

```

## 1.2 Duplicate filtering

```{r Remove duplicates}

# Read in the post-HWE filtered data
setwd(output_data_dir)
filter7 <- readRDS("filter7-HWE.RData")

# Convert to gds format
filter7_gen <- gi2gl(gl2gi(filter7))
gl2gds(filter7_gen, outfile="filter7-HWE.gds", outpath = output_data_dir)

# Read in gds file in SNPRelate format
setwd(output_data_dir)
Snp_gds <- snpgdsOpen("filter7-HWE.gds") 
genotype_snp <- read.gdsn(index.gdsn(Snp_gds,"genotype"))

# MLE Kinship Estimation
snp_MLE <- snpgdsIBDMLE(Snp_gds, autosome.only = FALSE)
snp_ibd.coeff <- snpgdsIBDSelection(snp_MLE)

# Close the gds file
snpgdsClose(Snp_gds)

# Plots to examine duplicate threshold

setwd(paste0(dups_result_dir,"/_PLOTS"))
jpeg(filename = "filter7-k0-k1-plot.jpg")
plot(snp_ibd.coeff$k0, snp_ibd.coeff$k1, xlim=c(0,1), ylim=c(0,1), 
     xlab="k0", ylab="k1", pch=20, col=alpha("black",0.4))
lines(c(0,1), c(1,0), col="red", lty=2)
dev.off()

setwd(paste0(dups_result_dir,"/_PLOTS"))
jpeg(filename = "filter7-kinship-plot.jpg")
plot(snp_ibd.coeff$kinship,
     ylab="Kinship",xlab="SNP Index",col=alpha("black",0.4),pch=20)
abline(h=0.1875,col="orange",lty=2)
abline(h=0.45,col="red",lty=2)
dev.off()

# Duplicates
dups <- snp_ibd.coeff[(snp_ibd.coeff[,6]>0.40),]

# Save SNP IBD coefficients table for identified duplicates
setwd(dups_result_dir)
write.csv(dups,file = "Identified-duplicates-kinship-0.4.csv")

# Remove duplicates
filter8 <- gl.drop.ind(filter7, ind.list=dups$ID1, recalc = TRUE, mono.rm = TRUE)

# Save data with duplicates removed
setwd(output_data_dir)
saveRDS(filter8, file = "filter8-no-dups.RData")

```

## 1.3 Outlier filtering

```{r Arlequin - make input}

# INPUT WITH SITES AS POPS

# Load the data
setwd(output_data_dir)
filter7 <- readRDS("filter7-HWE.RData")

# Basic prep
filter7@pop <- as.factor(filter7@other$ind.metrics$site_code)
filter7.1 <- gl.drop.pop(filter7, pop.list = c("BR","SA"),recalc = TRUE,mono.rm = TRUE) # Remove sites with n < 5

# Convert to structure format
gl2structure(filter7.1, ploidy=2, outpath = output_data_dir, outfile = "Arlequin-input-sites.str", addcolumns = filter7.1@pop,  exportMarkerNames = TRUE)

# Save the data used to generate this str file
setwd(output_data_dir)
saveRDS(filter7.1, file = "filter7.1-HWE-n5.RData")


# INPUT WITH REGIONS AS POPS

filter7@pop <- as.factor(filter7@other$ind.metrics$pop)

gl2structure(filter7, ploidy=2, outpath = output_data_dir, outfile = "Arlequin-input-regions.str", addcolumns = filter7@pop,  exportMarkerNames = TRUE)


# LEAVE R HERE: use PGDSpider and Arlequin

# In PGDSpider - convert the .str file from STRUCTURE to STRUCTURE (diploid, 2 row format, missing data -9, pop, ind and loc names included, SNP format with number repeats), then convert STRUCTURE to ARLEQUIN (same settings, in Arlequid settings of spd file choose SNP, keep rest as defaults). Then use the .arp file generated in Arlequin, and choose settings -> Genetic Structure -> Detecting loci under selection (check this and keep defaults). Make sure to set pops to group 1 by changing the 0 to 1 under Structure Editor then click Update Project. Then click Start.

```

```{r Arlequin - process output}

# FUNCTION: read qvalue trunc
qvalue_truncp <- function(p, fdr.level = NULL, pfdr = FALSE, lfdr.out = TRUE, pi0 = NULL, ...) {
  # Argument checks
  p_in <- qvals_out <- lfdr_out <- p
  rm_na <- !is.na(p)
  p <- p[rm_na]
  if (min(p) < 0 || max(p) > 1) {
    stop("p-values not in valid range [0, 1].")
  } else if (!is.null(fdr.level) && (fdr.level <= 0 || fdr.level > 1)) {
    stop("'fdr.level' must be in (0, 1].")
  }
  p <- p / max(p)
  # Calculate pi0 estimate
  if (is.null(pi0)) {
    pi0s <- pi0est(p, ...)
  } else {
    if (pi0 > 0 && pi0 <= 1)  {
      pi0s = list()
      pi0s$pi0 = pi0
    } else {
      stop("pi0 is not (0,1]")
    }
  }
  
  # Calculate q-value estimates
  m <- length(p)
  i <- m:1L
  o <- order(p, decreasing = TRUE)
  ro <- order(o)
  if (pfdr) {
    qvals <- pi0s$pi0 * pmin(1, cummin(p[o] * m / (i * (1 - (1 - p[o]) ^ m))))[ro]
  } else {
    qvals <- pi0s$pi0 * pmin(1, cummin(p[o] * m /i ))[ro]
  }
  qvals_out[rm_na] <- qvals
  # Calculate local FDR estimates
  if (lfdr.out) {
    lfdr <- lfdr(p = p, pi0 = pi0s$pi0, ...)
    lfdr_out[rm_na] <- lfdr
  } else {
    lfdr_out <- NULL
  }
  
  # Return results
  if (!is.null(fdr.level)) {
    retval <- list(call = match.call(), pi0 = pi0s$pi0, qvalues = qvals_out,
                   pvalues = p_in, lfdr = lfdr_out, fdr.level = fdr.level,
                   significant = (qvals <= fdr.level),
                   pi0.lambda = pi0s$pi0.lambda, lambda = pi0s$lambda,
                   pi0.smooth = pi0s$pi0.smooth)
  } else {
    retval <- list(call = match.call(), pi0 = pi0s$pi0, qvalues = qvals_out,
                   pvalues = p_in, lfdr = lfdr_out, pi0.lambda = pi0s$pi0.lambda,
                   lambda = pi0s$lambda, pi0.smooth = pi0s$pi0.smooth)
  }
  class(retval) <- "qvalue"
  return(retval)
}

# Once Arlequin finishes running, make sure the output folders are available here: outlier_result_dir

# RESULTS WITH SITES AS POPS

folder <- "Arlequin-input-sites-STR-ARL.res"

# Read in the Arlequin result
setwd(outlier_result_dir)
Arlequin_FST <- read.table(paste0(folder,"/fdist2_ObsOut.txt"), header = F, skip=1, fill=T)
names(Arlequin_FST) <- c("Locus",     "ObsHet",     "ObsFST", "FSTPvalue", "OneMinusFSTquantile")

# Deletion of rows that have pvalue of 2
Arlequin_FST <- Arlequin_FST[which(Arlequin_FST$FSTPvalue<2),]

# Convert p to q values (with FDR of 5%)
Arl_FST_pval <- as.numeric(Arlequin_FST$FSTPvalue)
Arl_FST_qval <- qvalue_truncp(Arl_FST_pval, fdr.level = 0.05)
Arlequin_FST$FSTQvalue <- Arl_FST_qval$qvalues

# Check for outliers
Arlequin_OutlierData <- Arlequin_FST[which(Arlequin_FST$FSTQvalue < 0.05),]

setwd(outlier_result_dir)
write.table(Arlequin_OutlierData, "Arlequin-sites-outliers-results.txt", row.names = F)
Arlequin_OutlierData <- read.table("Arlequin-sites-outliers-results.txt", header = T)

Arlequin_Outliers <- as.data.frame(Arlequin_OutlierData$Locus)
names(Arlequin_Outliers) <- c("LocusNumber")

# Order of loci should match same order as genlight object used to create the str file
setwd(output_data_dir)
filter7.1 <- readRDS("filter7.1-HWE-n5.RData")
Arlequin_outlier_names <- filter7.1$loc.names[Arlequin_OutlierData$Locus]

# Save txt file of locus names
setwd(outlier_result_dir)
write.table(Arlequin_outlier_names,file = "Arlequin-sites-outliers-by-locus-names.txt",row.names = FALSE,col.names = FALSE)
write.table(Arlequin_OutlierData$Locus,file = "Arlequin-sites-outliers-by-index.txt",row.names = FALSE,col.names = FALSE)



# RESULTS WITH REGIONS AS POPS

folder <- "Arlequin-input-regions-STR-ARL.res"

# Read in the Arlequin result
setwd(outlier_result_dir)
Arlequin_FST <- read.table(paste0(folder,"/fdist2_ObsOut.txt"), header = F, skip=1, fill=T)
names(Arlequin_FST) <- c("Locus",     "ObsHet",     "ObsFST", "FSTPvalue", "OneMinusFSTquantile")

# Deletion of rows that have pvalue of 2
Arlequin_FST <- Arlequin_FST[which(Arlequin_FST$FSTPvalue<2),]

# Convert p to q values (with FDR of 5%)
Arl_FST_pval <- as.numeric(Arlequin_FST$FSTPvalue)
Arl_FST_qval <- qvalue_truncp(Arl_FST_pval, fdr.level = 0.05)
Arlequin_FST$FSTQvalue <- Arl_FST_qval$qvalues

# Check for outliers
Arlequin_OutlierData <- Arlequin_FST[which(Arlequin_FST$FSTQvalue < 0.05),]

setwd(outlier_result_dir)
write.table(Arlequin_OutlierData, "Arlequin-regions-outliers-results.txt", row.names = F)
Arlequin_OutlierData <- read.table("Arlequin-regions-outliers-results.txt", header = T)

Arlequin_Outliers <- as.data.frame(Arlequin_OutlierData$Locus)
names(Arlequin_Outliers) <- c("LocusNumber")

# Order of loci should match same order as genlight object used to create the str file (check output/input etc)
setwd(output_data_dir)
filter7 <- readRDS("filter7-HWE.RData")
Arlequin_outlier_names <- filter7$loc.names[Arlequin_OutlierData$Locus]

# Save txt file of locus names
setwd(outlier_result_dir)
write.table(Arlequin_outlier_names,file = "Arlequin-regions-outliers-by-locus-names.txt",row.names = FALSE,col.names = FALSE)
write.table(Arlequin_OutlierData$Locus,file = "Arlequin-regions-outliers-by-index.txt",row.names = FALSE,col.names = FALSE)


```

```{r OutFLANK}

# OUTFLANK WITH SITES AS POPS

# Load the data
setwd(output_data_dir)
filter7.1 <- readRDS("filter7.1-HWE-n5.RData")

# Outflank can be run from within dartR. To be able to run this function the packages qvalue (from bioconductor) and outflank (from github) needs to be installed. 

#Left and RightTrimFraction = proportion of loci that are trimmed from the lower (or upper) end of the range of Fst before the likelihood function is applied. Hmin = minimum heterozygosity threshold required before loci are included in calculations. qthreshold = false discovery rate.
outflank <- gl.outflank(filter7.1, plot = TRUE, LeftTrimFraction = 0.05, RightTrimFraction = 0.05, Hmin = 0.1, qthreshold = 0.05)

# Check whether to use FST or FSTnoCorr (no correction) - should be roughly correlated
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-fst-vs-fstnocorr.jpg")
plot(outflank$outflank$results$FST, outflank$outflank$results$FSTNoCorr, main="Outflank Fst vs FstNoCorr (no correction)",xlab="FST",ylab="FST (no correction)")
abline(0, 1) # Checking the effect of sample size on Fst 
dev.off()

# Check if any loci with low He (<0.1) have high Fst
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-Het-by-Fst-nocorr.jpg")
plot(outflank$outflank$results$He, outflank$outflank$results$FSTNoCorr, pch=20, col=alpha("black",0.2),xlab="Heterozygosity",ylab="FST (no correction)",main="Outflank Fst by He")
dev.off()

# Check Distribution with and without Low He loci (check highest FstNoCorr in df to set range (e.g. 0,0.54 for PEL, and 0,1 for SNI)
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-Fst-histogram-all-loci.jpg")
hist(outflank$outflank$results$FSTNoCorr,main="FSTNoCorr All Loci",xlab="FST (no correction)",breaks = 20) # all loci
dev.off()

setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-Fst-histogram-He01-loci.jpg")
hist(outflank$outflank$results$FSTNoCorr[outflank$outflank$results$He>0.1], main="FSTNoCorr He > 0.1 Loci",xlab="FST (no correction)",breaks = 20) # He >0.1 loci
dev.off()

# Plot the ditribution of Fst with the chi squared distribution (this is also produced by the gl.outflank wrapper above, but putting here for more info)
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-Fst-histogram-with-chisquare-disttribution.jpg")
OutFLANKResultsPlotter(outflank$outflank, withOutliers = TRUE, NoCorr = TRUE, 
                       binwidth = 0.005, Zoom = FALSE, RightZoomFraction = 0.05, 
                       titletext = NULL, Hmin = 0.1) 
dev.off()


# check p values (all) -a uniform distribution suggests lack of outliers - if there's a peak at 0 there are outliers.
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-p-vals-all.jpg")
hist(outflank$outflank$results$pvalues,breaks=seq(0,1, by=0.01),col="grey",main="Outflank histogram p values All",xlab="All p values")
dev.off()

# check p values (right tail) - again a peak at 0 suggests outliers
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-p-vals-right-tail.jpg")
hist(outflank$outflank$results$pvaluesRightTail,breaks=seq(0,1, by=0.01),col="grey",main="Outflank histogram p values Right-tail",xlab = "Right tail p values")
dev.off()

# Identify outliers
top_candidates <- outflank$outflank$results$qvalues<0.05 & outflank$outflank$results$He>0.1

setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-sites-outliers-top-candidates.jpg")
plot(outflank$outflank$results$He, outflank$outflank$results$FSTNoCorr, xlab="Expected Heterozygosity", ylab="FST", pch=20, col="grey", main = "Outflank Top Candidates")
points(outflank$outflank$results$He[top_candidates], outflank$outflank$results$FSTNoCorr[top_candidates], pch=20, col="red")
dev.off()

# list top candidates
topcan <- outflank$outflank$results[top_candidates,]

# Save outlier candidate list
setwd(outlier_result_dir)
write.csv(topcan,file="Outflank-sites-top-candidates.csv")



# OUTFLANK WITH REGIONS AS POPS

# Load the data
setwd(output_data_dir)
filter7 <- readRDS("filter7-HWE.RData")

#Left and RightTrimFraction = proportion of loci that are trimmed from the lower (or upper) end of the range of Fst before the likelihood function is applied. Hmin = minimum heterozygosity threshold required before loci are included in calculations. qthreshold = false discovery rate.
outflank <- gl.outflank(filter7, plot = TRUE, LeftTrimFraction = 0.05, RightTrimFraction = 0.05, Hmin = 0.1, qthreshold = 0.05)
outflank

# Check whether to use FST or FSTnoCorr (no correction) - should be roughly correlated
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-fst-vs-fstnocorr.jpg")
plot(outflank$outflank$results$FST, outflank$outflank$results$FSTNoCorr, main="Outflank Fst vs FstNoCorr (no correction)",xlab="FST",ylab="FST (no correction)")
abline(0, 1) # Checking the effect of sample size on Fst 
dev.off()

# Check if any loci with low He (<0.1) have high Fst
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-Het-by-Fst-nocorr.jpg")
plot(outflank$outflank$results$He, outflank$outflank$results$FSTNoCorr, pch=20, col=alpha("black",0.2),xlab="Heterozygosity",ylab="FST (no correction)",main="Outflank Fst by He")
dev.off()

# Check Distribution with and without Low He loci (check highest FstNoCorr in df to set range (e.g. 0,0.54 for PEL, and 0,1 for SNI)
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-Fst-histogram-all-loci.jpg")
hist(outflank$outflank$results$FSTNoCorr,main="FSTNoCorr All Loci",xlab="FST (no correction)",breaks = 20) # all loci
dev.off()

setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-Fst-histogram-He01-loci.jpg")
hist(outflank$outflank$results$FSTNoCorr[outflank$outflank$results$He>0.1], main="FSTNoCorr He > 0.1 Loci",xlab="FST (no correction)",breaks = 20) # He >0.1 loci
dev.off()

# Plot the ditribution of Fst with the chi squared distribution (this is also produced by the gl.outflank wrapper above, but putting here for more info)
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-Fst-histogram-with-chisquare-disttribution.jpg")
OutFLANKResultsPlotter(outflank$outflank, withOutliers = TRUE, NoCorr = TRUE, 
                       binwidth = 0.005, Zoom = FALSE, RightZoomFraction = 0.05, 
                       titletext = NULL, Hmin = 0.1) 
dev.off()


# check p values (all) -a uniform distribution suggests lack of outliers - if there's a peak at 0 there are outliers.
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-p-vals-all.jpg")
hist(outflank$outflank$results$pvalues,breaks=seq(0,1, by=0.01),col="grey",main="Outflank histogram p values All",xlab="All p values")
dev.off()

# check p values (right tail) - again a peak at 0 suggests outliers
setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-p-vals-right-tail.jpg")
hist(outflank$outflank$results$pvaluesRightTail,breaks=seq(0,1, by=0.01),col="grey",main="Outflank histogram p values Right-tail",xlab = "Right tail p values")
dev.off()

# Identify outliers
top_candidates <- outflank$outflank$results$qvalues<0.05 & outflank$outflank$results$He>0.1

setwd(paste0(outlier_result_dir,"/_PLOTS"))
jpeg(filename = "Outflank-regions-outliers-top-candidates.jpg")
plot(outflank$outflank$results$He, outflank$outflank$results$FSTNoCorr, xlab="Expected Heterozygosity", ylab="FST", pch=20, col="grey", main = "Outflank Top Candidates")
points(outflank$outflank$results$He[top_candidates], outflank$outflank$results$FSTNoCorr[top_candidates], pch=20, col="red")
dev.off()

# list top candidates
topcan <- outflank$outflank$results[top_candidates,]

# Save outlier candidate list
setwd(outlier_result_dir)
write.csv(topcan,file="Outflank-regions-top-candidates.csv")

```

```{r BayeScan - make input}

# INPUT WITH SITES AS POPS

# Load the data
setwd(output_data_dir)
filter7.1 <- readRDS("filter7.1-HWE-n5.RData")

# Convert to bayescan format
setwd(output_data_dir)
gl2bayescan(filter7.1, outfile="Bayescan-sites-input.txt", outpath= ".")

# INPUT WITH REGIONS AS POPS

# Load the data
setwd(output_data_dir)
filter7 <- readRDS("filter7-HWE.RData")

# Convert to bayescan format
setwd(output_data_dir)
gl2bayescan(filter7, outfile="Bayescan-regions-input.txt", outpath= ".")

# LEAVE R HERE: Run file in Bayescan GUI, then come back to R. See settings in paper.

```

```{r BayeScan - process output}

# FUNCTION: Plot Bayescan
plot_bayescan<-function(res,FDR=0.05,size=1,pos=0.35,highlight=NULL,name_highlighted=F,add_text=T)
  {if (is.character(res))
    res=read.table(res)
  colfstat=5
  colq=colfstat-2
  highlight_rows=which(is.element(as.numeric(row.names(res)),highlight))
  non_highlight_rows=setdiff(1:nrow(res),highlight_rows)
  outliers=as.integer(row.names(res[res[,colq]<=FDR,]))
  ok_outliers=TRUE
  if (sum(res[,colq]<=FDR)==0)
    ok_outliers=FALSE;
  res[res[,colq]<=0.0001,colq]=0.0001

  # plot
  plot(log10(res[,colq]),res[,colfstat],xlim=rev(range(log10(res[,colq]))),xlab="log10(q value)",ylab=names(res[colfstat]),type="n")
  points(log10(res[non_highlight_rows,colq]),res[non_highlight_rows,colfstat],pch=19,cex=size)
  if (name_highlighted) {
    if (length(highlight_rows)>0) {
      text(log10(res[highlight_rows,colq]),res[highlight_rows,colfstat],row.names(res[highlight_rows,]),col="red",cex=size*1.2,font=2)
    }
  }
  else {
    points(log10(res[highlight_rows,colq]),res[highlight_rows,colfstat],col="red",pch=19,cex=size)
    # add names of loci over p and vertical line
    if (ok_outliers & add_text) {
      text(log10(res[res[,colq]<=FDR,][,colq])+pos*(round(runif(nrow(res[res[,colq]<=FDR,]),1,2))*2-3),res[res[,colq]<=FDR,][,colfstat],row.names(res[res[,colq]<=FDR,]),cex=size)
    }
  }
  lines(c(log10(FDR),log10(FDR)),c(-1,1),lwd=2)
  return(list("outliers"=outliers,"nb_outliers"=length(outliers)))
}


# Once BayeScan finishes running, make sure the output folders are available here: outlier_result_dir

# RESULTS WITH SITES AS POPS

# Load Bayescan results
folder <- "Bayescan-with-site-locations"
setwd(paste0(outlier_result_dir,"/",folder))
res <- read.table("output_fst.txt", header=TRUE)
Bayescan_res <- plot_bayescan(res)

# Match locus names against input data
# Note that bayescan and arlequin don't retain locus names, so they just number them according to the order in the input file
setwd(output_data_dir)
filter7.1 <- readRDS("filter7.1-HWE-n5.RData")
Bayescan_outlier_names <- filter7.1$loc.names[Bayescan_res$outliers]

# Save outliers
setwd(outlier_result_dir)
write.table(Bayescan_res$outliers, file = "Bayescan-sites-outliers-by-index.txt", row.names = FALSE,col.names = FALSE)
write.table(Bayescan_outlier_names,file = "Bayescan-sites-outliers-by-locus-names.txt",row.names = FALSE,col.names = FALSE)


# RESULTS WITH REGIONS AS POPS

# Load Bayescan results
folder <- "Bayescan-with-region-locations"
setwd(paste0(outlier_result_dir,"/",folder))
res <- read.table("output_fst.txt", header=TRUE)
Bayescan_res <- plot_bayescan(res)

# Match locus names against input data
setwd(output_data_dir)
filter7 <- readRDS("filter7-HWE.RData")
Bayescan_outlier_names <- filter7$loc.names[Bayescan_res$outliers]

# Save outliers
setwd(outlier_result_dir)
write.table(Bayescan_res$outliers, file = "Bayescan-regions-outliers-by-index.txt", row.names = FALSE,col.names = FALSE)
write.table(Bayescan_outlier_names,file = "Bayescan-regions-outliers-by-locus-names.txt",row.names = FALSE,col.names = FALSE)

```

```{r Remove outlier loci}

# BY SITES AS POPS

# Outflank
setwd(outlier_result_dir)
outflank_outliers <- read.csv("Outflank-sites-top-candidates.csv", header = TRUE)
outflank_outliers <- c("68796050-48-C/G", "68811727-16-C/G")

# Arlequin
setwd(outlier_result_dir)
arlequin_outliers <- read.table("Arlequin-sites-outliers-by-locus-names.txt")
arlequin_outliers <- arlequin_outliers$V1

# Bayescan
setwd(outlier_result_dir)
bayescan_outliers <- read.table("Bayescan-sites-outliers-by-locus-names.txt")
bayescan_outliers <- bayescan_outliers$V1

# Outliers detected by ALL 3 methods
outliers_in_3_methods <- intersect(c(outflank_outliers,arlequin_outliers),bayescan_outliers)

# Outliers detected by at least 2 methods
Bayes_outflank_shared <- intersect(outflank_outliers,bayescan_outliers)
Arl_outflank_shared <- intersect(outflank_outliers,arlequin_outliers)
Arl_bayes_shared <- intersect(bayescan_outliers,arlequin_outliers)
outliers_in_2_methods <- unique(unlist(c(Bayes_outflank_shared,Arl_outflank_shared,Arl_bayes_shared)))

# Outliers detected by at least 1 method = all outliers
outliers_in_1_method <- unique(unlist(c(outflank_outliers,arlequin_outliers,bayescan_outliers)))

# BY REGIONS AS POPS

# Outflank
setwd(outlier_result_dir)
outflank_outliers <- read.csv("Outflank-regions-top-candidates.csv", header = TRUE)
outflank_outliers <- c() # no outliers

# Arlequin
setwd(outlier_result_dir)
arlequin_outliers <- read.table("Arlequin-regions-outliers-by-locus-names.txt")
arlequin_outliers <- arlequin_outliers$V1

# Bayescan
setwd(outlier_result_dir)
bayescan_outliers <- read.table("Bayescan-regions-outliers-by-locus-names.txt")
bayescan_outliers <- bayescan_outliers$V1

# Outliers detected by ALL 3 methods
outliers_in_3_methods_regions <- intersect(c(outflank_outliers,arlequin_outliers),bayescan_outliers)

# Outliers detected by at least 2 methods
Bayes_outflank_shared_regions <- intersect(outflank_outliers,bayescan_outliers)
Arl_outflank_shared_regions <- intersect(outflank_outliers,arlequin_outliers)
Arl_bayes_shared_regions <- intersect(bayescan_outliers,arlequin_outliers)
outliers_in_2_methods_regions <- unique(unlist(c(Bayes_outflank_shared_regions,Arl_outflank_shared_regions,Arl_bayes_shared_regions)))

# Outliers detected by only 1 method = all outliers
outliers_in_1_method_regions <- unique(unlist(c(outflank_outliers,arlequin_outliers,bayescan_outliers)))

# All outliers detected based on sites/regions
sites_regions_shared_3_methods <- intersect(outliers_in_3_methods,outliers_in_3_methods_regions)
sites_regions_shared_2_methods <- intersect(outliers_in_2_methods,outliers_in_2_methods_regions)
sites_regions_shared_1_methods <- intersect(outliers_in_1_method,outliers_in_1_method_regions)
all_outliers <- unique(unlist(outliers_in_1_method,outliers_in_1_method_regions))

# Summary results
setwd(outlier_result_dir)
sink(file = "outlier-results-summary.txt")
print("Outliers by site - detected in 3 methods")
length(outliers_in_3_methods)
print("Outliers by site - detected in 2 methods")
length(outliers_in_2_methods)
print("Outliers by site - detected in at least 1 method")
length(outliers_in_1_method)
print("Outliers by region - detected in 3 methods")
length(outliers_in_3_methods_regions)
print("Outliers by region - detected in 2 methods")
length(outliers_in_2_methods_regions)
print("Outliers by region - detected in at least 1 method")
length(outliers_in_1_method_regions)
print("Outliers by site or region - detected in 3 methods")
length(sites_regions_shared_3_methods)
print("Outliers by site or region - detected in 2 methods")
length(sites_regions_shared_2_methods)
print("Outliers by site or region - detected in at least 1 method")
length(sites_regions_shared_1_methods)
print("ALL POTENTIAL OUTLIERS")
length(all_outliers)
sink()


# Save datasets with and without consensus outliers, also excluding duplicate samples

# Load the data
setwd(output_data_dir)
filter8 <- readRDS("filter8-no-dups.RData")

# Removing all putative outlier loci at both site and region level - generating a putatively neutral dataset
filter9 <- gl.drop.loc(filter8, loc.list = all_outliers)
filter9

# Save putatively neutral dataset
setwd(output_data_dir)
saveRDS(filter9, file = "filter9-neutral-loci.RData")
saveRDS(filter9, file = "BTF-3-155-14808-neutral-loci.RData")

# Save in genlight format
filter9gen <- gi2gl(gl2gi(filter9))
setwd(output_data_dir)
saveRDS(filter9gen,file = "BTF-3-155-14808-neutral-genlight.RData")

```
