---
title: "2-sex-inference"
author: "Skye Davis"
date: "2026-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Workflow
This script takes the unfiltered SNP data generated by DArTseq (SNPs called using DArT’s proprietary pipeline DArTSoft14TM) and maps loci to the Z and W chromosomes of a close relative to infer the sex of each sample.


# Set up

```{r Packages}

# Data manipulation & BLAST
library(dartR) # v2.9.7
library(dplyr) # v1.1.4

# Sex inference
library(mclust) # v6.1.1
source("https://raw.githubusercontent.com/drobledoruiz/conservation_genomics/main/filter.sex.linked/filter.sex.linked.R")
source("https://raw.githubusercontent.com/drobledoruiz/conservation_genomics/main/infer.sex/infer.sex.R")

# Plotting
library(ggplot2) # v3.5.1
library(ggpubr) # v0.6.0

# Other attached packages
library(adegenet) # v2.1.10
library(ade4) # v1.7-22

```

```{r Directories}

# Main directory for data
data_dir <- paste0(getwd(),"/data")

# Input data directory for this script
input_data_dir <- paste0(data_dir,"/filtered-dart-data")

# Output data directory for this script
output_data_dir <- paste0(data_dir,"/sex-data")
dir.create(output_data_dir, recursive = TRUE)

# Results directories for this script

sex_result_dir <- paste0(getwd(),"/results/2-sex-inference")
dir.create(sex_result_dir, recursive = TRUE)
dir.create(paste0(sex_result_dir,"/_PLOTS"), recursive = TRUE)

```

# Analysis

## 2.1 Sex inference

```{r Prepare BLAST input}

# Get sample names from filtered dataset
setwd(input_data_dir)
data <- readRDS("BTF-3-155-14808-neutral-genlight.RData")
samples_to_retain <- data@ind.names

# Import raw data before any filtering
setwd(paste0(data_dir,"/unfiltered-dart-data"))
unfiltered <- gl.read.dart(filename = "Report_DPoep23-8916_1_moreOrders_SNP_mapping_2-renamed.csv", 
                           ind.metafile = "BTF_pop_info.csv")

# Retain only post-filter samples
unfiltered2 <- gl.keep.ind(unfiltered, ind.list = samples_to_retain, recalc = TRUE, mono.rm = TRUE)

# Save files
setwd(output_data_dir)
saveRDS(unfiltered2,file = "BTF-unfiltered-data-for-sex-inference.RData")

```

```{r Perform BLAST}

# Download and install blast+
# https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
# Set directory for the blast bin
blast_dir <- "C:/Users/kskye/OneDrive/Desktop/NCBI/blast-2.15.01/bin"

# Import unfiltered data with final samples
setwd(output_data_dir)
data <- readRDS("BTF-unfiltered-data-for-sex-inference.RData")

# Set location of reference genomes
genome_dir <- paste(output_data_dir,"/ref_genomes",sep = "")

# Convert to genlight
data2 <- gi2gl(gl2gi(data))

# Create TrimmedSequence column
data2@other$loc.metrics$TrimmedSequence <- data2@other$loc.metrics$TrimmedSequenceRef

# Perform the basic blast with no filters
setwd(blast_dir)
Z_blast <- gl.blast(data2,ref_genome = paste(genome_dir,"/Tguttata_NC_044241.2_Z-chrom.fasta", sep=""),Percentage_identity = 0,bitscore = 0)
W_blast <- gl.blast(data2,ref_genome = paste(genome_dir,"/Tguttata_NC_045028.1_W-chrom.fasta", sep=""),Percentage_identity = 0,bitscore = 0)

# Write the genotype and locus metrics to csv
gl.write.csv(Z_blast, outfile = "unfiltered-Z-loci-raw.csv", outpath = sex_result_dir)
gl.write.csv(W_blast, outfile = "unfiltered-W-loci-raw.csv", outpath = sex_result_dir)

# Read back in as data frame
setwd(sex_result_dir)
Z_blast <- read.csv("unfiltered-Z-loci-raw.csv", header = TRUE)
W_blast <- read.csv("unfiltered-W-loci-raw.csv", header = TRUE)

# Extract results from loc.metrics
Z_blast_result <- Z_blast %>% select(-AlleleSequenceRef, -AlleleSequenceSnp, -TrimmedSequenceRef, -TrimmedSequenceSnp, -Chrom_Zebra_finch_v1p, -ChromPosTag_Zebra_finch_v1p, -ChromPosSnp_Zebra_finch_v1p, -AlnCnt_Zebra_finch_v1p, -AlnEvalue_Zebra_finch_v1p, -Strand_Zebra_finch_v1p, -monomorphs, -OneRatio, -PIC)
W_blast_result <- W_blast %>% select(-AlleleSequenceRef, -AlleleSequenceSnp, -TrimmedSequenceRef, -TrimmedSequenceSnp, -Chrom_Zebra_finch_v1p, -ChromPosTag_Zebra_finch_v1p, -ChromPosSnp_Zebra_finch_v1p, -AlnCnt_Zebra_finch_v1p, -AlnEvalue_Zebra_finch_v1p, -Strand_Zebra_finch_v1p, -monomorphs, -OneRatio, -PIC)

# Remove non-mapped loci
Z_blast_result2 <- Z_blast_result %>% filter(!is.na(sacc))
W_blast_result2 <- W_blast_result %>% filter(!is.na(sacc))

# Remove the first row. It contains pop info for each sample and we don't need it for this analysis
Z_blast_result2 <- Z_blast_result2[-1,]
W_blast_result2 <- W_blast_result2[-1,]

# Save BLAST data
setwd(sex_result_dir)
write.csv(Z_blast_result2, file = "unfiltered-Z-loci.csv", row.names = FALSE)
write.csv(W_blast_result2, file = "unfiltered-W-loci.csv", row.names = FALSE)

```

```{r Filter BLAST results}

# Load unfiltered BLAST results
setwd(sex_result_dir)
Z_blast_result2 <- read.csv(file = "unfiltered-Z-loci.csv", header = TRUE)
W_blast_result2 <- read.csv(file = "unfiltered-W-loci.csv", header = TRUE)

# Retain loci which map with >=80% identity
Z_blast_result3 <- Z_blast_result2 %>% filter(pident >= 80)
W_blast_result3 <- W_blast_result2 %>% filter(pident >= 80)

# Retain loci which map with evalue < 1e-10
Z_blast_result4 <- Z_blast_result3 %>% filter(evalue < 0.0000000001)
W_blast_result4 <- W_blast_result3 %>% filter(evalue < 0.0000000001)

# Remove duplicate cloneids (secondaries)
Z_blast_result5 <- distinct(Z_blast_result4, CloneID, .keep_all = TRUE)
W_blast_result5 <- distinct(W_blast_result4, CloneID, .keep_all = TRUE)

# Remove loci with poor RepAvg
Z_blast_result6 <- Z_blast_result5 %>% filter(RepAvg >= 0.98)
W_blast_result6 <- W_blast_result5 %>% filter(RepAvg >= 0.98)

# Remove pseudoautosomal loci (approximation)
# For PAR1, retain loci that have subject.start > 400,000.
# For PAR2 on Z chromosome, retain loci that have subject.end < Z_length - 330,000
# For PAR2 on W chromosome, retain loci that have subject.end < W_length - 330,000

# For BTF, the zebra finch Z chrom is 75,396,176 and W is 20,846,394.
Z_length <- 75396176
W_length <- 20846394
Z_blast_result7 <- Z_blast_result6 %>% filter(sstart > 400000 & send < (Z_length - 330000))
W_blast_result7 <- W_blast_result6 %>% filter(sstart > 400000 & send < (W_length - 330000))

# Retain loci that only map to either the Z or the W (not both)
dups <- intersect(Z_blast_result7$AlleleID, W_blast_result7$AlleleID)
Z_blast_result8 <- Z_blast_result7 %>% filter(!AlleleID %in% dups)
W_blast_result8 <- W_blast_result7 %>% filter(!AlleleID %in% dups)

# Save BLAST results after filtering
setwd(sex_result_dir)
write.csv(Z_blast_result8, file = "filtered-Z-loci.csv", row.names = FALSE)
write.csv(W_blast_result8, file = "filtered-W-loci.csv", row.names = FALSE)

```

```{r Calculate sex inference metrics}

# Load filtered BLAST results
setwd(sex_result_dir)
Z_blast_result8 <- read.csv(file = "filtered-Z-loci.csv", header = TRUE)
W_blast_result8 <- read.csv(file = "filtered-W-loci.csv", header = TRUE)

# Get the sample genotype data on its own
first_sample <- "C_BTF1"

Z_geno <- Z_blast_result8 %>%
  select(all_of(first_sample):last_col())

W_geno <- W_blast_result8 %>%
  select(all_of(first_sample):last_col())

# Count total loci
n_Z_loci <- nrow(Z_geno)
n_W_loci <- nrow(W_geno)

# Total non-missing loci per sample
n_Z_called <- colSums(!is.na(Z_geno))
n_W_called <- colSums(!is.na(W_geno))

# Count of missing W loci per sample
n_W_missing <- colSums(is.na(W_geno))

# Count of heterozygous Z loci per sample
n_Z_het <- colSums(Z_geno == 1, na.rm = TRUE)/colSums(!is.na(Z_geno))

# Compile counts
sex_stats <- data.frame(n_Z_loci = n_Z_loci,
                        n_W_loci = n_W_loci,
                        n_Z_called = n_Z_called,
                        n_W_called = n_W_called,
                        n_W_missing = n_W_missing,
                        n_Z_het = n_Z_het)
sex_stats

# Calculate sex inference metrics
sex_stats2 <- sex_stats %>%
  mutate(prop_W_miss = n_W_missing / n_W_loci,
         Z_W_ratio = n_Z_called / n_W_called,
         Z_het = n_Z_het / n_Z_called)
sex_stats2

# Retain only the sex inference metrics
sex_stats3 <- sex_stats2 %>% select(prop_W_miss, Z_W_ratio, Z_het)
sex_stats3

# Save sex inference metrics
setwd(sex_result_dir)
write.csv(sex_stats3, file = "sex-inference-metrics.csv", row.names = TRUE)

```

```{r Infer sex with mclust}

# Load sex inference metrics
setwd(sex_result_dir)
sex_stats3 <- read.csv(file = "sex-inference-metrics.csv", header = TRUE)
rownames(sex_stats3) <- sex_stats3$X
sex_stats3 <- sex_stats3 %>% select(-X)
sex_stats3

# Scale the data
sex_stats4 <- as.data.frame(scale(sex_stats3, center = TRUE, scale = TRUE))
sex_stats4

# Run the model clustering (G = 2 sets the model to examine only 2 clusters in the data)
mclust_result <- Mclust(data = sex_stats4, G = 2)

# Examine the cluster classifications
mclust_result2 <- data.frame(mclust_result$classification, mclust_result$uncertainty, mclust_result$z[,1], mclust_result$z[,2])
colnames(mclust_result2) <- c("Cluster", "Uncertainty", "Cluster1_prob", "Cluster2_prob")
mclust_result2

# Add mclust results to original unscaled data
sex_stats5 <- cbind(sex_stats3, mclust_result2)
sex_stats5$Cluster <- as.factor(sex_stats5$Cluster)
sex_stats5

# How many sample assigned to each cluster?
table(sex_stats5$Cluster)

# Colours for clusters
cluster_cols <- c("1" = "#FFCD00", "2" = "#00843D")

# Plot sex inference metrics coloured by cluster
A <- ggplot(data = sex_stats5, aes(x = Z_het, y = prop_W_miss, color = Cluster))+
  geom_point(alpha = 0.5)+
  labs(x = "Z heterozygosity", y = "W missing rate", color = "Cluster")+
  scale_color_manual(values = cluster_cols)+
  stat_ellipse()
A

B <- ggplot(data = sex_stats5, aes(x = Z_het, y = Z_W_ratio, color = Cluster))+
  geom_point(alpha = 0.5)+
  labs(x = "Z heterozygosity", y = "Z/W ratio", color = "Cluster")+
  scale_color_manual(values = cluster_cols)+
  stat_ellipse()
B

C <- ggplot(data = sex_stats5, aes(x = prop_W_miss, y = Z_W_ratio, color = Cluster))+
  geom_point(alpha = 0.5)+
  labs(x = "W missing rate", y = "Z/W ratio", color = "Cluster")+
  scale_color_manual(values = cluster_cols)+
  stat_ellipse()
C

D <- ggplot(data = sex_stats5, mapping = aes(x = Cluster1_prob, y = Cluster2_prob, col = Cluster)) +
  geom_point()+
  labs(x = "Cluster 1", y = "Cluster 2")+
  scale_color_manual(values = cluster_cols)
D

# Add a new column to clarify sex - uses dyplr mutate
sex_stats6 <- mutate(sex_stats5, Sex = ifelse(Cluster == '1', 'F', 'M'))
sex_stats6

# Save sex inference results
setwd(sex_result_dir)
write.csv(sex_stats6,file = "sexing-mcluster-results.csv")

# Save plot for appendix
plot_margin <- theme(plot.margin=margin(t = 10, r = 10, b = 5, l = 10, unit = "pt"))
plot_theme <- theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = NA), plot.background = element_rect(fill=NA), panel.border = element_rect(fill=NA),legend.position = "none") 
text_size <- theme(axis.title.x = element_text(size = 10), axis.text.x = element_text(size = 8), axis.title.y = element_text(size = 10), axis.text.y = element_text(size = 8),plot.title=element_text(size=11,face="bold",hjust=0),legend.text = element_text(size=6))

A2 <- A + plot_margin + plot_theme + text_size
B2 <- B + plot_margin + plot_theme + text_size
C2 <- C + plot_margin + plot_theme + text_size
D2 <- D + plot_margin + plot_theme + text_size

## TIFF and sized for Science Journal
setwd(paste0(sex_result_dir,"/_PLOTS"))
tiff("sexing-mclust-summary-plot.tif",width = 17.5, height = 12, unit='cm', res=1200)
ggarrange(A2,B2,C2,D2,
          labels = c("A", "B", "C","D"),
          ncol = 2, nrow = 2)
dev.off()


```

```{r Append sex to genlight object}

# Load genlight data
setwd(input_data_dir)
data <- readRDS("BTF-3-155-14808-neutral-genlight.RData")
data

# Load sex inference data
setwd(sex_result_dir)
sex_stats6 <- read.csv(file = "sexing-mcluster-results.csv", header = TRUE)
sex_stats6 <- sex_stats6 %>% dplyr::rename(id = X)
sex_stats6

# Append new metadata
new_metadata <- data@other$ind.metrics %>% left_join(sex_stats6[, c("id", "Sex")], by = "id")
data@other$ind.metrics <- new_metadata

# Rename metadata column headers
colnames(data@other$ind.metrics) <- c("id","pop","survey","season","sampler","site","site_code","capture_time","release_time","recapture","FTA_blood","field_sample_reference","blood_sample_batch","lon","lat","service","plate_location","sex")

# Save genlight
setwd(output_data_dir)
saveRDS(data,"BTF-3-155-14808-neutral-genlight-sexinfo.RData")

```


## 2.2 Sex-linked loci

```{r Remove any sex-linked loci}

# Load data
setwd(output_data_dir)
data <- readRDS("BTF-3-155-14808-neutral-genlight-sexinfo.RData")

# Identify sex-linked loci in filtered dataset
filtered <- filter.sex.linked(gl = data,
                                  system = "zw",
                                  plots = TRUE,
                                  parallel = TRUE)

# Save results
setwd(sex_result_dir)
write.csv(filtered$results.table, file = "initial-sex-linked-loci-stats.csv")

# How many sex-linked loci identified?
print("W-linked loci")
nLoc(filtered$w.linked)
print("Z-linked loci")
nLoc(filtered$z.linked)
print("loci with sex-biased call rates")
nLoc(filtered$sex.biased)
print("ZW Gametologs")
nLoc(filtered$gametolog) 
print("Autosomal loci")
nLoc(filtered$autosomal)

# No sex-linked loci detected, proceeding with presumed autosomal SNP set
setwd(output_data_dir)
saveRDS(data,"BTF-3-155-14808-neutral-auto-genlight-sexinfo.RData")


```

